---
version: "2"
checks:
  argument-count:
    config:
      # Default: 4
      threshold: 7
  method-complexity:
    config:
      # We have multiple methods where CodeClimate measures the
      # Cognitive Complexity at 50 or higher.
      #
      # I think it's reasonable to focus CodeClimate on the really high
      # ones, and lower this value later.
      # - @duckinator
      #
      # Default: 5.
      threshold: 20
  method-count:
    config:
      # Default: 20
      threshold: 30
  method-lines:
    config:
      # We have individual methods with 175 lines of code.
      # I think it's reasonable to focus on things like that for now.
      # - @duckinator
      #
      # Default: 25.
      threshold: 100
  file-lines:
    config:
      # There is a correlation between the files CodeClimate rates the
      # worst and the biggest biggest files.
      #
      # I am trying to prioritize the files with the most problems, so
      # I chose a threshold that seems to accomplish this.
      #
      # Sorting https://codeclimate.com/github/rubygems/rubygems/code
      # by "lines of code" and "maintainability" can be useful to see if
      # this correlation still exists.
      #
      # - @duckinator
      #
      # Default: 250.
      threshold: 400
  return-statements:
    # This was adding flagging a lot of functions where having many
    # return statements made sense.
    # - @duckinator
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
- bundler/bundler.gemspec
- "bundler/*.md"
- bundler/lib/bundler/ssl_certs/*.pem
- bundler/lib/bundler/vendor/**/*
- bundler/lib/bundler/templates/**/*.tt
- bundler/man/*
- bundler/spec/**/*
- bundler/Rakefile
- test/**/*
- lib/rubygems/optparse.rb
- lib/rubygems/optparse/**/*
- lib/rubygems/tsort/**/*
