---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - "bundler/**.rb"
  - "bundler/bin/*"
  - "bundler/exe/*"
exclude_paths:
- bundler/bundler.gemspec
- "bundler/*.md"
- bundler/lib/bundler/ssl_certs/*.pem
- bundler/lib/bundler/vendor/**/*
- bundler/lib/bundler/templates/**/*.tt
- bundler/man/*
- bundler/spec/**/*
- bundler/Rakefile
- test/**/*
- lib/rubygems/optparse.rb
- lib/rubygems/optparse/**/*
- lib/rubygems/tsort/**/*
