inherit_from: .rubocop.yml

AllCops:
  Include:
    - bundler/**/*.rb
    - bundler/**/*.gemspec
    - bundler/**/Rakefile
    - bundler/**/Gemfile
    - bundler/**/*.rake
    - bundler/**/Executable
    - bundler/**/Executable.*
  Exclude:
    - bin/*
    - pkg/**/*
    - tmp/**/*
    - util/**/*
    - bundler/tmp/**/*
    - bundler/lib/bundler/vendor/**/*

# Naming

Naming/ConstantName:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

# Performance

Performance/RegexpMatch:
  Enabled: true

# Style

Style/ClassVars:
  Enabled: true

Style/FormatString:
  Enabled: true

# 1.8.7 support
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/LineEndConcatenation:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true
