require: rubocop-performance

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bundler/**/*'
    - 'lib/rubygems/resolver/molinillo/**/*'
    - 'lib/rubygems/tsort/**/*'
    - 'lib/rubygems/optparse/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

Layout/EmptyLineAfterMagicComment:
  Enabled: true
  Exclude:
    - test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec

Layout/AccessModifierIndentation:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

# Force Unix line endings.
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/Debugger:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Naming/HeredocDelimiterCase:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true
  ForbiddenDelimiters:
    - ^RB$

Naming/MemoizedInstanceVariableName:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Security/Open:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/Next:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - test/rubygems/test_gem.rb
    - test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec

Style/RedundantBegin:
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/Dir:
  Enabled: true

Style/Encoding:
  Enabled: true
  Exclude:
    - test/rubygems/specifications/foo-0.0.1-x86-mswin32.gemspec

Style/ExpandPathArguments:
  Enabled: true

Style/EvalWithLocation:
  Enabled: true

Style/IfInsideElse:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Not:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/SafeNavigation:
  Enabled: true
  MaxChainLength: 1

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Having these make it easier to *not* forget to add one when adding a new
# value and you can simply copy the previous line.
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
