inherit_from: .rubocop.yml

AllCops:
  Include:
    - bundler/**/*.rb
    - bundler/**/*.gemspec
    - bundler/**/Rakefile
    - bundler/**/Gemfile
    - bundler/**/*.rake
    - bundler/**/Executable
    - bundler/**/Executable.*
  Exclude:
    - bin/*
    - pkg/**/*
    - tmp/**/*
    - util/**/*
    - bundler/tmp/**/*
    - bundler/lib/bundler/vendor/**/*


# Lint

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/Void:
  Enabled: true

# Layout

Layout/EmptyLineAfterMagicComment:
  Enabled: true

# Naming

Naming/BlockParameterName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

# Performance

Performance/RegexpMatch:
  Enabled: true

# Style

Style/AsciiComments:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# 1.8.7 support
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/LineEndConcatenation:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/Next:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/Semicolon:
  Enabled: true
