AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bundler/**/*'
    - 'lib/rubygems/resolver/molinillo/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Layout/AccessModifierIndentation:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

# Force Unix line endings.
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
