# DO NOT EDIT
# This file is auto-generated by build scripts.
# See:  rake update_version
#--
# Copyright 2006 by Chad Fowler, Rich Kilmer, Jim Weirich and others.
# All rights reserved.
# See LICENSE.txt for permissions.
#++

module Gem
  RubyGemsVersion = '0.8.99.2'
end
