.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BUNDLE\-PACKAGE" "1" "July 2022" "" ""
.
.SH "NAME"
\fBbundle\-package\fR \- Renamed command\. See \fBbundle\-cache(1)\fR
.
.SH "SYNOPSIS"
\fBbundle package\fR
.
.SH "DESCRIPTION"
This command was renamed to \fBbundle cache\fR in Bundler 2\.1 and now is an alias of \fBbundle\-cache(1)\fR \fIbundle\-cache\.1\.html\fR\.
