#!/usr/bin/env ruby
# frozen_string_literal: true

seed = begin
         Integer(ENV["SEED"])
       rescue
         abort "Specify the failing seed as the SEED environment variable"
       end

gemdir = `gem env gemdir`.chomp
ENV["RUBYOPT"] = "-Ilib:bundler/lib:test:#{gemdir}/gems/minitest-server-1.0.5/lib"
ENV["MTB_VERBOSE"] = "2"

begin
  minitest_bisect = Gem.bin_path("minitest-bisect", "minitest_bisect")
rescue Gem::GemNotFoundException
  abort "Install minitest-bisect gem to run a rubygems test suite bisection"
end

load minitest_bisect
