#!/usr/bin/env ruby

class Tool

  def initialize(name)
    @name = name
  end

  def bundler?
    @name == 'bundler'
  end

  def rubygems?
    @name == 'rubygems'
  end

  def dir
    if rubygems?
      File.expand_path('../..', __FILE__)
    else
      File.expand_path('../../bundler', __FILE__)
    end
  end

end

TOOL = Tool.new(ENV.fetch("TEST_TOOL") { abort "must specify a TEST_TOOL" })

def run(command, args = [])
  Dir.chdir(TOOL.dir) do
    unless system(command, *args)
      abort "running `#{command} #{args.join(" ")}` failed"
    end
  end
end

def with_retries(attempts = 3)
  yield
rescue StandardError, SystemExit => e
  attempts -= 1
  if attempts > 0
    warn "Command failed (#{e}). Retrying #{attempts -= 1} more times."
    retry
  else
    raise
  end
end

case ARGV
when %w(before_script)
  if TOOL.rubygems?
    run('ruby', %W(-I lib bin/gem uninstall executable-hooks gem-wrappers bundler-unload -x --force -i #{`gem env home`.strip}@global))

    # shipped gems in 2.3.8
    run('rake', 'setup')

    run('gem', %w(list --details))
    run('gem', %w(env))
  else
    if ENV["BDV"]
      run('git', %W(reset --hard origin/#{ENV["BDV"]}))
    end

    with_retries { run('rake', %w(spec:travis:deps)) }
  end
when %w(rubocop)
  run('gem', %w(install rubocop -v ~>0.61.1))
  run('util/rubocop')
when %w(script)
  if TOOL.rubygems?
    run('rake test')
  else
    run('rake', %w(spec:travis -t))
  end
else
  abort "unknown args #{ARGV.inspect}"
end
