#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  load Gem.bin_path("rubocop", "rubocop", "~> 0.61.1")
rescue Gem::GemNotFoundException
  abort "Install the rubocop gem (~> 0.61.1) to run a static analysis"
end
