name: ruby-core

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ruby_core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rubygems, bundler]
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev bison autoconf ruby
      - name: Prepare the working directory
        run: |
          mkdir ruby
          mkdir rubygems
      - uses: actions/checkout@v2
        with:
          repository: ruby/ruby
          path: ruby/ruby
      - name: Build Ruby
        run: |
          autoconf
          ./configure -C --disable-install-doc
          make -j2
        working-directory: ruby/ruby
      - uses: actions/checkout@v2
        with:
          path: rubygems/rubygems
      - name: Test RubyGems
        run: |
          ruby tool/sync_default_gems.rb rubygems
          make test-all TESTS="rubygems -j2"
        working-directory: ruby/ruby
        continue-on-error: true
        if: matrix.target == 'rubygems'
      - name: Test Bundler
        run: |
          ruby tool/sync_default_gems.rb bundler
          make test-bundler
        working-directory: ruby/ruby
        continue-on-error: true
        if: matrix.target == 'bundler'
