name: ubuntu-rvm

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_rvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.3.8', 'ruby-head', 'jruby-9.2.9.0' ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
          sudo chmod -R go-w /opt
      - name: Set up RVM
        run: |
          curl -sSL https://get.rvm.io | bash
      - name: Set up Ruby
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install ${{ matrix.ruby }} --binary --autolibs=disable
          rvm --default use ${{ matrix.ruby }}
      - name: Test rubygems
        run: |
          source $HOME/.rvm/scripts/rvm
          util/ci.sh before_script
          util/ci.sh script
        env:
          TEST_TOOL: rubygems
        if: matrix.ruby == 'jruby-9.2.9.0' || matrix.ruby == '2.3.8'
      - name: Test bundler
        run: |
          source $HOME/.rvm/scripts/rvm
          BDV=master util/ci.sh before_script
          util/ci.sh script
        continue-on-error: true
        env:
          TEST_TOOL: bundler
        if: matrix.ruby == 'ruby-head'
    timeout-minutes: 60
